sudo: false
cache: npm
branches:
  only:
    - main

jobs:
  include:
    - stage: api-test
      language: php
      php: '7.4'
      before_script:
        - cd api
        - composer install
      script: php artisan test
    - stage: api-deploy
      language: php
      php: '7.4'
      script: make deploy-api
    - stage: client-test
      language: node.js
      php: '12.0'
      before_script:
        - cd client
        - yarn install
      script: yarn test
    - stage: client-deploy
      language: node.js
      php: '12.0'
      before_script:
        - cd client
        - yarn install
      script: yarn deploy

stages:
  - api-test
  - api-deploy
  - client-test
  - client-deploy