dist: xenial
os: linux
language: php
php: 7.4.12
cache:
  npm: true
  directories:
  - client/node_modules
  - api/vendor
  - client/dist
  # we also need to cache folder with Cypress binary
  - /home/travis/.cache/Cypress
branches:
  only:
  - main
jobs:
  include:
  - stage: install-dependencies
    name: Installing composer vendors
    language: php
    php: 7.4.12
    before_script:
    - cd api
    script:
    - composer install
  - stage: test
    name: Run api tests
    language: php
    php: 7.4.12
    before_script:
    - cd api
    - cp .env.example .env
    - php artisan key:generate
    script:
    - php artisan test
  - stage: api-deploy
    name: Deploy api to heroku
    language: node_js
    node_js: 14.15.1
    script:
    - echo *** DEPLOYING ***
    deploy:
      provider: heroku
      api_key:
        secure: kib/aOJW6k9kEEXASRbIAIeACToF0kq+sO48fqkWLGvn5u0+V2cajltlEweQPV6UwDwZZNvvSDp2MQTx2lxYh5YGj4F5bPhVVIdiaJJgZ5ZBJK74RMUaUIXkGSeHvklRY3rosTH9my7yDhwXljMo99U7KSHJMkhzBk85dumtaJV5K6zz5jFji/Nn0BVkgJIet2jlfqgtw7bClKxTBQjnbKgZZpamlLoD7wkoSXZBpzjL2QdN4zKkEqeyIMqPiQ5YQzxaCT8FKyydGXlkbEoWCItIBM0GaFrv3CZ2F1dv3psrMX5Zr80c3nPZaza+zem7H7wlJ/nP48nZkgfXZ22B2kCjQnAgzJlhgHP4MagyFu0ctjmk3rDrXyfOYjOvqaxdqis3IO0lAwBX4IFPGtzCI0558RWOIDmmo9lKnQgiM37+m2RH0YOGgaZy75tuzeizHUvImQgcjPoJDtJ4BumxIXt8ngE0YLDofj3viXb3j26o7RDD3E7QA2M78c8OE7OFmUnL4GbqAdWSMbDt7xRaLoxO/la6JPgYCPrc+Ev3xIpwhkDW7YjDNhyfGX/tXxIlt1CHnJqer0U9HQCa1LxNmZ20+04yn3FUTpDt5wS4UuIYqMDr0yT+MUSPjt2GyUcL8KRnuq5qzsa4H51ezav1wqXa01F+mgjsv4mNoljG8Mc=
      app: dannyyassine-secret-santa
      on: main
      skip_cleanup: 'true'
  - stage: install-dependencies
    name: Installing node_modules
    language: node_js
    node_js: 14.15.1
    before_script:
    - cd client
    script:
    - yarn install
  - stage: test
    name: Run client tests
    language: node_js
    node_js: 14.15.1
    addons:
      apt:
        packages:
          # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
          - libgconf-2-4
    before_script:
    - cd api
    - composer install
    - php artisan serve
    - cd ..
    - cd client
    - yarn test:cypress:install
    script:
    - yarn test
  - stage: test
    name: Test client build
    language: node_js
    node_js: 14.15.1
    before_script:
      - cd client
    script:
      - yarn build
  - stage: client-deploy
    name: Deploy client to Firebase
    language: node_js
    node_js: 14.15.1
    before_script:
      - cd client
    script:
      - yarn build
      - ls -ls
      - cd ..
    deploy:
      provider: firebase
      token:
        secure: ePXdrECuUbcc8qPDwgVA9GC0ovxbACKTRxvbKPwzuNP5i0K5DedIquhEaLEWHFzAUYy+NCkiqOa7aMAZ9Fx6KyGRp7boahCyMHe2Bw+CWBZP1AGHCyUIaCcnOA71S9xXWqrWcpC0eO/XzdnEFt3ZJGFoX1ct2Y1AHskhXAAjIx+jyX+ldm9ouEzSRd4YNDHeHj8fmLOuIp68JH4kZx/6hHdVbxlKoiBCFxF/wswWu7tAu0qMTwyHKvT1RX+iBk8ayoZAaK5YGvJSl1i7+CFGxTTp5dxey8pQzWBCLYXB8BDcnZ3VMUxPINubzhr8vnjE+Tm+FHB8TIVVk9h+daKm2I6Y4Vr1vtkC/yqLkcBY0JhKdH28D52m4RBTLwTg4iJ/j2F8drZns/S+WM41x/nF6058hMLIJRf9x2qm3rAAPPxN5Wl6IJB3H+uUsVISrfHeBTTdbLbx8Zn+DMPLVwKHYXw+I3DBvQG6mojax6A/x+7RajsskV0BaP3LlbU0f5t6fpdUsinGjvxAvMAf9MCielCvmOGv7tQkP/gtv0hdH22Bxi0M7nRGU6cUGBysoxlPxYcMj4hhwjfru3XjT/q3EGLaAyq/lz6JMLxH3xjVvHuYA+XLrpAlHG0zFx+dWkRWAyVArYvUCDiHKZ0JecmXq1JeK/aILcsrY5/dM1MmCl4=
      project: virtual-secret-santa
      on: main
      skip_cleanup: 'true'
stages:
- install-dependencies
- test
- api-deploy
- client-deploy