dist: xenial
os: linux
language: php
cache:
  directories:
  - client/node_modules
  - api/vendor
branches:
  only:
  - main
jobs:
  include:
  - stage: install-dependencies
    language: php
    php: 7.4.12
    before_script:
    - cd api
    script:
    - composer install
  - stage: test
    language: php
    php: 7.4.12
    before_script:
    - cd api
    - cp .env.example .env
    - php artisan key:generate
    script:
    - php artisan test
  - stage: api-deploy
    language: node_js
    node_js: 14.15.1
    script:
    - echo *** DEPLOYING ***
    deploy:
      provider: heroku
      api_key:
        secure: lOZpbfgk/FOpeFEForZcDg+IBXucNpbtsz3X0Zu+US6r6RvcR+sjcaOEvcIs67lCvkrmMV7ANNPzAxwTpADOXFIKkyOIMJOJrUsrvbokQutcQCsTYyo+oKFLQGV3ZE++mzvWoYzD1G92jslvePGv404zCDFejdQjI+NIXqq+6sFQXh03Cbum37mQufJJDHn8pKDGlN9eAx4zHSQFc+3z96w93Mi0ZYukUCMsa/8HALvAP2m2XcXQsWfvkESIXIkWuXV/kdscbjG4sHPum/5IsHS4p65Z9ybo0NoLr+waOdvabG1/z23zVtDVuRnbhiZzgebNs1lJ/iYCOub5WZvZsIhw5f/szCs1KLgMP+Da9Kcvrr1D+vLLAnikptv3yC+UyOCjnzdSjyI52qXOHPzqZiZZPQDQa05eM+cgKzVIsqvuOk3TRgeoMiAJN21MKlZRQZHhYldVLw7lJmwtGXMPvTe0Iv/FkuXZGB9PHdh8wWC/4/KTCIh6MA/Hsgr2w3asQPfRgxu06WH2+kIBnyqoYhaQVZesCrgKvtwbIFjuekO81woBic/q6qnW4MJT4FOBWqcbjhbtGY6IZBDxJJmmKZw/y6ppCYikSfI1+/kBMLA2V1AJQzfg78X0mh1KYPj3r2xdYcvzzq2YNi98/iZOCXu+n/CY7BlL3ftP+rEDkf8=
      app: dannyyassine-secret-santa
      on: main
      skip_cleanup: 'true'
  - stage: install-dependencies
    language: node_js
    node_js: 14.15.1
    before_script:
    - cd client
    script:
    - yarn install
  - stage: test
    language: node_js
    node_js: 14.15.1
    before_script:
    - cd client
    script:
    - yarn test
  - stage: client-deploy
    language: node_js
    node_js: 14.15.1
    script: skip
    deploy:
      provider: firebase
      token:
        secure: ePXdrECuUbcc8qPDwgVA9GC0ovxbACKTRxvbKPwzuNP5i0K5DedIquhEaLEWHFzAUYy+NCkiqOa7aMAZ9Fx6KyGRp7boahCyMHe2Bw+CWBZP1AGHCyUIaCcnOA71S9xXWqrWcpC0eO/XzdnEFt3ZJGFoX1ct2Y1AHskhXAAjIx+jyX+ldm9ouEzSRd4YNDHeHj8fmLOuIp68JH4kZx/6hHdVbxlKoiBCFxF/wswWu7tAu0qMTwyHKvT1RX+iBk8ayoZAaK5YGvJSl1i7+CFGxTTp5dxey8pQzWBCLYXB8BDcnZ3VMUxPINubzhr8vnjE+Tm+FHB8TIVVk9h+daKm2I6Y4Vr1vtkC/yqLkcBY0JhKdH28D52m4RBTLwTg4iJ/j2F8drZns/S+WM41x/nF6058hMLIJRf9x2qm3rAAPPxN5Wl6IJB3H+uUsVISrfHeBTTdbLbx8Zn+DMPLVwKHYXw+I3DBvQG6mojax6A/x+7RajsskV0BaP3LlbU0f5t6fpdUsinGjvxAvMAf9MCielCvmOGv7tQkP/gtv0hdH22Bxi0M7nRGU6cUGBysoxlPxYcMj4hhwjfru3XjT/q3EGLaAyq/lz6JMLxH3xjVvHuYA+XLrpAlHG0zFx+dWkRWAyVArYvUCDiHKZ0JecmXq1JeK/aILcsrY5/dM1MmCl4=
      project: virtual-secret-santa
stages:
- install-dependencies
- test
- api-deploy
- client-deploy
