dist: xenial
os: linux
language: php
cache:
  directories:
  - client/node_modules
  - api/vendor
branches:
  only:
  - main
jobs:
  include:
  - stage: install-dependencies
    language: php
    php: 7.4.12
    before_script:
    - cd api
    script:
    - composer install
  - stage: test
    language: php
    php: 7.4.12
    before_script:
    - cd api
    - cp .env.example .env
    - php artisan key:generate
    script:
    - php artisan test
  - stage: api-deploy
    language: node_js
    node_js: 14.15.1
    script:
    - echo *** DEPLOYING ***
    deploy:
      provider: heroku
      api_key:
        secure: USB0zxfS+uBM/7TRBW9yGk94BIctSP7dAgx4n9AK+MOdxTOBtRVLVW7AcMzAeRxYhDuq3rpe0ZAE4rzCdoQCG5rSdIezPdQoCsZWD1eO0AqY732tn0KyGkmU/dHtM18qNz68y4uv2GVtwirB13qrBzDjOPvZIN056VOHHygx/Rhk2jEHvJM5FiswhFCwLTJvpjqCDqkUQ5pdI/k/YwnyaCsRyi+hNO2nZfJZzr3WxAMJrcYbQ+f8J3yHidiAZGTkOWINpy1T7WiT8h6ayIU9jm/7zJ7WzIVJpoe92YL+JgS8jIDmrOwYeblr4glu9A6PqCOWSwl+7udJblkyrbYTNkX3d6MZUYgdcM9lY+/lYVzRh3M+GACAoPuWflJ7OEdZYkRq2dxTT69SR1FJTVVpjQlgutz8Yea5bf+z17/BnixYM+AUmPUIkGkeGhbqzIJVgd1rfrOZsLTz97XhkAUABkb6Vl/OUOijiULNKs8+zPjBKP9TfGLvz369mwZHRq1QOijS/QotARGiHCUwR17Xl66v32nRhZGaJHWtV/iYmnlqMsSGEmoQ+i81trFdO00IrZbIDyCTnj633hTbG9JeXCJV4K78gb0hzpktt6CX6jlH2iWZEELyg+3GY5BwjNXZBFBW1TpiIM/zG+FQSq9dlBBvWPkDnEvKxLO+bxAs8Xg=
      app: dannyyassine-secret-santa
      on: main
  - stage: install-dependencies
    language: node_js
    node_js: 14.15.1
    before_script:
    - cd client
    script:
    - yarn install
  - stage: test
    language: node_js
    node_js: 14.15.1
    before_script:
    - cd client
    script:
    - yarn test
  - stage: client-deploy
    language: node_js
    node_js: 14.15.1
    script: skip
    deploy:
      provider: firebase
      token:
        secure: ePXdrECuUbcc8qPDwgVA9GC0ovxbACKTRxvbKPwzuNP5i0K5DedIquhEaLEWHFzAUYy+NCkiqOa7aMAZ9Fx6KyGRp7boahCyMHe2Bw+CWBZP1AGHCyUIaCcnOA71S9xXWqrWcpC0eO/XzdnEFt3ZJGFoX1ct2Y1AHskhXAAjIx+jyX+ldm9ouEzSRd4YNDHeHj8fmLOuIp68JH4kZx/6hHdVbxlKoiBCFxF/wswWu7tAu0qMTwyHKvT1RX+iBk8ayoZAaK5YGvJSl1i7+CFGxTTp5dxey8pQzWBCLYXB8BDcnZ3VMUxPINubzhr8vnjE+Tm+FHB8TIVVk9h+daKm2I6Y4Vr1vtkC/yqLkcBY0JhKdH28D52m4RBTLwTg4iJ/j2F8drZns/S+WM41x/nF6058hMLIJRf9x2qm3rAAPPxN5Wl6IJB3H+uUsVISrfHeBTTdbLbx8Zn+DMPLVwKHYXw+I3DBvQG6mojax6A/x+7RajsskV0BaP3LlbU0f5t6fpdUsinGjvxAvMAf9MCielCvmOGv7tQkP/gtv0hdH22Bxi0M7nRGU6cUGBysoxlPxYcMj4hhwjfru3XjT/q3EGLaAyq/lz6JMLxH3xjVvHuYA+XLrpAlHG0zFx+dWkRWAyVArYvUCDiHKZ0JecmXq1JeK/aILcsrY5/dM1MmCl4=
      project: virtual-secret-santa
stages:
- install-dependencies
- test
- api-deploy
- client-deploy
