dist: xenial
os: linux
language: php
cache:
  directories:
  - client/node_modules
  - api/vendor
branches:
  only:
  - main
jobs:
  include:
  - stage: install-dependencies
    language: php
    php: 7.4.12
    before_script:
    - cd api
    script:
    - composer install
  - stage: test
    language: php
    php: 7.4.12
    before_script:
    - cd api
    - cp .env.example .env
    - php artisan key:generate
    script:
    - php artisan test
  - stage: api-deploy
    language: node_js
    node_js: 14.15.1
    script:
    - echo *** DEPLOYING ***
    deploy:
      provider: heroku
      api_key:
        secure: oBLeWWwljiIAejCCsZX/94hihj9M2apPZ23hHisMN7kXSqbS+tmqaJLglCEtmN68t7i/qEyX7BxBTH+vyZkCNBsoa2+c8fIn6/UwKdZH0dvkC0cFnCAtUhmoqD2tkjSfpbOyC07jpQDE0jYInT5oJjmvw9l+HgrEWoPH6vyqzfHo8Z1i06TXYhmB5PVTaFvA2VFDk9A72dIGOiITOvXLUZZj6aeAlLAeTw8KVmLs+QnY+abe/9J479/ioPb1iH/alRoh5KZOLEwXZua9v2gKpX4Rlz9KkdCOnFSLf5Cwhh48CrmiKpIwQ4sZuVvAI31aCtZHBY1nxN0SbwLh68O+bQHknc+5RR8sRFpq2RmaW7B3BDn+17dbd71fIhG80vDwaw81V47WsW2mI/5a3mww7l1xqG+QD5YtgoLftnPZvC103mAHSuGoQL7aOSOeV3tvbq0PetZnJb1kg54DurDp8iF8nFa/uAdt2lJhU7A6PUaL0x+xFBsYbJbXTSC96DH6W/0O1CylEemlXPsiNldoQrYqvfwk9ldO/A12zny3ugtAqN8kgS8Zppbk+LFgdkqBFRXNm9ksPjva+CJldPJZagyV4N6Y9Rmw6aXnujIQ8Z5nfEZAs20wuuaw0VuvmtLoD7DgAaryVTyYq6pTVnPHLylvy+YbbQ36LZ376cxHleM=
      app: dannyyassine-secret-santa
      on: main
  - stage: install-dependencies
    language: node_js
    node_js: 14.15.1
    before_script:
    - cd client
    script:
    - yarn install
  - stage: test
    language: node_js
    node_js: 14.15.1
    before_script:
    - cd client
    script:
    - yarn test
  - stage: client-deploy
    language: node_js
    node_js: 14.15.1
    before_script:
    - cd client
    script: yarn deploy
stages:
- api-deploy
- client-deploy
