dist: xenial
os: linux
language: php
cache:
  directories:
  - client/node_modules
  - api/vendor
branches:
  only:
  - main
jobs:
  include:
  - stage: composer-install
    language: php
    php: 7.4.12
    before_script:
      - cd api
    script:
      - composer install
  - stage: api-test
    language: php
    php: 7.4.12
    before_script:
      - cd api
      - cp .env.example .env
      - php artisan key:generate
    script:
      - php artisan test
  - stage: api-deploy
    language: node_js
    node_js: 14.15.1
    before_script:
      - chmod +x .travis/push.sh
    script:
      - echo *** DEPLOYING ***
      - . ./.travis/push.sh
  - stage: yarn-install
    language: node_js
    node_js: 14.15.1
    before_script:
      - cd client
    script:
      - yarn install
  - stage: client-test
    language: node_js
    node_js: 14.15.1
    before_script:
      - cd client
    script:
      - yarn test
  - stage: client-deploy
    language: node_js
    node_js: 14.15.1
    before_script:
      - cd client
    script: yarn deploy
stages:
  - api-deploy
    if: (branch = main)
  - client-deploy
    if: (branch = main)
