dist: xenial
os: linux
language: php
cache:
  directories:
  - client/node_modules
  - api/vendor
branches:
  only:
  - main
jobs:
  include:
  - stage: api-test
    language: php
    php: 7.4.12
    before_script:
    - cd api
    - cp .env.example .env
    - php artisan key:generate
    script:
    - composer install
    - php artisan test
  - stage: api-deploy
    language: node_js
    node_js: 14.15.1
    script:
    - echo *** DEPLOYING ***
    deploy:
      provider: heroku
      api_key:
        secure: IhnDcm2QcWZltGsjxJbeKGRa7tiT/RAbmPgTfwxpoVD2EuEUs5qKrJ8cElvaUNz3gEMnfLm+PyfJ+QSt95CVCZ43kkzOqIQ5caoOg0VvFvs3MX1NxIcD4bR0+Hbaq5cL/b4riPI8ne3OA9/7tYcC7NAH4E5VZy0PIoXxvxvelYF8roQ0IgGI9cYLn1N+t6lEKYYMVWwNdIA5ryOFsrAA++mWRJSMGCGWYm0LoTd4Ex965flOP4dGzcUt1zKELn/E3CziCqHkRdObLuuZBZmw6WLt8iYahyYKgnJKN9t2uqBBoQLjYakGKkWoLBqqooeVx5PoRghBU+JVC1cQ9iSBDIJr+V/vZgim1Brd+vGJq1NKU5rY9lQCrKWWFZgKA2m4m75pBLUwFHjafuq2Rin2nXQPoK69DkHlL8EA1w6jorkGFkTP9inx6P4XOg56XfIrtqNPPwEl4JUtOWBmSYVLiZQBCnyZyCUeo0l9Zlpo3omYMVWC558o8FjGl/Iz65ioCnklguENAm2U0+j8yaEJWuQSS8DUmbeNAQ4z0J18dsUeNt+YXeScVk9Mw7/3NSiBNpjcKfGHNx539D6HOAhwJxbC4BLhweCv/CZHN5RjtS70sMfZ47Tqt3zvuSMUgRSntSR5yP5Ms7u7dYICZKK5d12RCzG2ikuX5DPlxzf7RO0=
      app: dannyyassine-secret-santa
      on: main
  - stage: client-test
    language: node_js
    node_js: 14.15.1
    before_script:
    - cd client
    script:
    - yarn install
    - yarn test
  - stage: client-deploy
    language: node_js
    node_js: 14.15.1
    before_script:
    - cd client
    script: yarn deploy
stages:
- api-deploy
- client-deploy
